version: "3"
services:
  api:
    image: node
    # platform: linux
    container_name: api
    working_dir: /usr/app
    depends_on:
        - db
    environment:
      - ENABLE_CORS=true
    ports:
      - 3000:3000
    volumes: 
      # Montaje de volumen en Linux
      # - ${PWD}/UbicacionesApi:/usr/app
      # Montaje de volumen en Windows
      - ./UbicacionesApi:/usr/app
    command: npm run dev

  db:
    image: mysql:5.7.30
    # platform: linux
    container_name: mysql
    # El contenedor ejecutara los ficheros .sql que esten dentro de este directorio.
    working_dir: /docker-entrypoint-initdb.d
    environment:
        # Password for root access
        MYSQL_ROOT_PASSWORD: 'password'
    expose:
        # Opens port 3306 on the container
        - '3306'
    volumes: 
      # Montaje de volumen en Linux
      # - ${PWD}/UbicacionesApi/database:/docker-entrypoint-initdb.d
      # Montaje de volumen en Windows
      - ./UbicacionesApi/database:/docker-entrypoint-initdb.d
    restart: always

  app:
    image: ngch43/vue_app
    # platform: linux
    container_name: app
    depends_on:
        - api
    ports:
        - 80:80
    

