version: "2"
services:
  api:
    image: node
    container_name: api
    working_dir: /usr/app
    depends_on:
        - db
    ports:
      - 3000:3000
    volumes: 
      - ${PWD}/UbicacionesApi:/usr/app
    command: npm run dev

  db:
    image: mysql:5.7.30
    container_name: mysql
    # El contenedor ejecutara los ficheros .sql que esten dentro de este directorio.
    working_dir: /docker-entrypoint-initdb.d
    environment:
        # Password for root access
        MYSQL_ROOT_PASSWORD: 'password'
    expose:
        # Opens port 3306 on the container
        - '3306'
    volumes: 
      - ${PWD}/UbicacionesApi/database:/docker-entrypoint-initdb.d
    # command: mysql -e "source database.sql"
  app:
    image: node:13.14.0
    container_name: app
    working_dir: /app
    depends_on:
        - api
    ports:
        - 80:80
    volumes: 
        - ${PWD}/app:/app
    command: npm run serve -- --port 80
    

